"""Replace existing dialog Mock UI blocks in 10 article files with aligned versions
generated by keeply-mock-ui.py.
"""
import importlib.util
import re
from pathlib import Path

# Dynamically import keeply-mock-ui.py (hyphenated filename)
spec = importlib.util.spec_from_file_location("kmu", Path(__file__).parent / "keeply-mock-ui.py")
kmu = importlib.util.module_from_spec(spec)
spec.loader.exec_module(kmu)

ROOT = Path(__file__).resolve().parents[2]

TARGETS = [
    ("zh-tw", "windows-file-history-vs-backup", "windows-file-history-vs-backup_tw"),
    ("zh-cn", "windows-file-history-vs-backup", "windows-file-history-vs-backup_cn"),
    ("zh-tw", "windows-file-history-wrong-version", "windows-file-history-wrong-version_tw"),
    ("zh-cn", "windows-file-history-wrong-version", "windows-file-history-wrong-version_cn"),
    ("zh-tw", "what-keeply-saves-vs-backup-cloud", "what-keeply-saves-vs-backup-cloud_tw"),
    ("zh-cn", "what-keeply-saves-vs-backup-cloud", "what-keeply-saves-vs-backup-cloud_cn"),
    ("zh-tw", "3-2-1-backup-rule", "3-2-1-backup-rule_tw"),
    ("zh-cn", "3-2-1-backup-rule", "3-2-1-backup-rule_cn"),
    ("zh-tw", "hidden-cost-shared-folders", "hidden-cost-shared-folders_tw"),
    ("zh-cn", "hidden-cost-shared-folders", "hidden-cost-shared-folders_cn"),
]

# Match a dialog block: ┌── line, then any lines, until └── line (greedy until first └─)
DIALOG_PATTERN = re.compile(
    r"┌─+┐\n(?:.+\n)*?└─+┘",
    re.MULTILINE,
)


def is_save_dialog(block: str) -> bool:
    return "儲存版本" in block or "保存版本" in block


def main():
    for locale, slug, case_key in TARGETS:
        path = ROOT / f"content/{locale}/post/{slug}/index.md"
        if not path.exists():
            print(f"  [SKIP] missing: {path}")
            continue

        text = path.read_text(encoding="utf-8")
        is_cn = locale == "zh-cn"
        gen = kmu.dialog_cn if is_cn else kmu.dialog
        new_dialog = gen(**kmu.CASES[case_key])

        # Find dialog blocks and replace the save-version one
        replaced = 0
        def repl(m):
            nonlocal replaced
            block = m.group(0)
            if is_save_dialog(block) and replaced == 0:
                replaced += 1
                return new_dialog
            return block

        new_text = DIALOG_PATTERN.sub(repl, text)
        if replaced == 0:
            print(f"  [WARN] no save dialog found in {path}")
            continue
        path.write_text(new_text, encoding="utf-8")
        print(f"  [OK] {path}")


if __name__ == "__main__":
    main()
